import json, re

NEW_PROMPTS = [
    # === HEARTBREAK EXPANDED ===
    {"id":1451,"c":"Songwriting","l":"Any","t":"Heartbreak — Drunk Texting at 2AM","d":"Medium","r":4.7,"p":"Write lyrics about sending that drunk text you know you'll regret. Liquid courage making you say everything you've been holding in. The morning-after horror of reading what you sent. The three dots appearing then disappearing. Capture the desperate vulnerability of needing someone who's already gone."},
    {"id":1452,"c":"Songwriting","l":"Any","t":"Heartbreak — Returning Their Stuff","d":"Medium","r":4.7,"p":"Write lyrics about the ritual of returning each other's belongings after a breakup. Each item triggers a memory — their hoodie still smells like them, the book they never finished. The awkward doorstep handover. Trying to be mature when everything in you is screaming to hold on."},
    {"id":1453,"c":"Songwriting","l":"Any","t":"Heartbreak — First Christmas Alone","d":"Medium","r":4.8,"p":"Write lyrics about spending Christmas alone after a breakup. Everyone's coupled up, the empty seat at dinner, buying one less present. The cruel timing of heartbreak during the happiest season. Fairy lights feel like they're mocking you. Finding strength in solitude."},
    {"id":1454,"c":"Songwriting","l":"Any","t":"Heartbreak — Unfollowing Everywhere","d":"Simple","r":4.6,"p":"Write lyrics about the modern breakup ritual of unfollowing, muting, blocking. Digital detox from a person. Every platform is a landmine of memories. The urge to check versus the need to heal. Archiving photos you can't delete. Modern heartbreak in the social media age."},
    {"id":1455,"c":"Songwriting","l":"Any","t":"Heartbreak — They Moved On First","d":"Medium","r":4.8,"p":"Write lyrics about discovering your ex is already in a new relationship. The timeline doesn't add up — were they talking while you were together? The jealousy, the comparison, the questioning of everything. Trying to be happy for them when you're still broken."},

    # === LOVE EXPANDED ===
    {"id":1456,"c":"Songwriting","l":"Any","t":"Love — Kitchen Dancing","d":"Simple","r":4.8,"p":"Write lyrics about spontaneously dancing in the kitchen with your partner. No music needed, or maybe the radio's on. Bare feet on tile, laughing, burning dinner because you got lost in each other. The ordinary magic of domestic love. Pure warmth."},
    {"id":1457,"c":"Songwriting","l":"Any","t":"Love — Love Language Mismatch","d":"Medium","r":4.7,"p":"Write lyrics about two people who love each other but express it differently. One needs words, one shows through actions. The miscommunication, the frustration, learning to read their version of 'I love you.' Growing together through understanding."},
    {"id":1458,"c":"Songwriting","l":"Any","t":"Love — Second Chance Romance","d":"Medium","r":4.8,"p":"Write lyrics about reconnecting with someone years later and falling in love again. You've both changed, grown, become who you needed to be. The timing is finally right. Nervous like teenagers but wiser. A love story with a sequel."},
    {"id":1459,"c":"Songwriting","l":"Any","t":"Love — Protecting Your Peace","d":"Medium","r":4.7,"p":"Write lyrics about choosing a quiet, healthy love over passionate chaos. After years of drama, you found someone who feels like calm. It's not fireworks — it's a warm fireplace. Learning that real love doesn't have to hurt. Celebrating the beauty of boring."},
    {"id":1460,"c":"Songwriting","l":"Any","t":"Love — Love Letter Unsent","d":"Medium","r":4.8,"p":"Write lyrics structured as a love letter you never had the courage to send. Everything you feel but can't say face to face. The specific things about them that undo you. Folded paper in a drawer, words worn soft from re-reading. Will you ever give it to them?"},

    # === MENTAL HEALTH EXPANDED ===
    {"id":1461,"c":"Songwriting","l":"Any","t":"Mental Health — Burnout","d":"Medium","r":4.8,"p":"Write lyrics about complete burnout. Running on empty, the passion is gone, you're just going through the motions. Can't remember the last time you felt excited about anything. The guilt of needing to stop in a world that never does. Permission to rest."},
    {"id":1462,"c":"Songwriting","l":"Any","t":"Mental Health — Imposter Syndrome","d":"Medium","r":4.7,"p":"Write lyrics about feeling like a fraud. Everyone thinks you have it together but you're waiting to be exposed. Each success feels like luck, each compliment feels undeserved. The exhaustion of performing competence. You belong here — you just can't believe it yet."},
    {"id":1463,"c":"Songwriting","l":"Any","t":"Mental Health — ADHD Brain","d":"Medium","r":4.7,"p":"Write lyrics about living with ADHD. A million tabs open in your brain, hyperfocus then nothing, starting everything finishing nothing. The frustration of knowing you're capable but your brain won't cooperate. Society built for neurotypical people. Finding your own rhythm."},
    {"id":1464,"c":"Songwriting","l":"Any","t":"Mental Health — Panic Attack","d":"Advanced","r":4.8,"p":"Write lyrics describing a panic attack from the inside. Heart racing, can't breathe, walls closing in, convinced you're dying. Time distorts, reality fractures. Then the slow return — grounding yourself, counting breaths, coming back. The aftermath exhaustion. You survived again."},
    {"id":1465,"c":"Songwriting","l":"Any","t":"Mental Health — Asking for Help","d":"Medium","r":4.8,"p":"Write lyrics about the moment you finally ask for help. The hardest words: 'I'm not okay.' Breaking through pride, shame, and the fear of being a burden. The relief when someone says 'I'm here.' Strength isn't doing it alone — it's knowing when you can't."},

    # === STREET LIFE EXPANDED ===
    {"id":1466,"c":"Songwriting","l":"Any","t":"Street Life — County Lines","d":"Advanced","r":4.7,"p":"Write lyrics about county lines exploitation. Young kids being groomed and used to run drugs to small towns. The manipulation, the fear, the isolation from family. Not glorifying — exposing the truth. The adults who profit while children take the risk. Urgent social commentary."},
    {"id":1467,"c":"Songwriting","l":"Any","t":"Street Life — Prison Letters","d":"Advanced","r":4.8,"p":"Write lyrics as letters exchanged between someone in prison and their partner outside. The loneliness on both sides, the promises to change, the reality of time. Visits behind glass, phone calls that cost too much. Love tested by concrete walls and barbed wire."},
    {"id":1468,"c":"Songwriting","l":"Any","t":"Street Life — The Getaway Driver","d":"Advanced","r":4.7,"p":"Write lyrics from the perspective of a getaway driver. Waiting in the car, engine running, heart pounding. Everything that could go wrong playing in your head. The seconds feel like hours. When they finally jump in — the adrenaline, the sirens, the aftermath. Cinematic tension."},

    # === NEW THEME: TECHNOLOGY & DIGITAL AGE ===
    {"id":1469,"c":"Songwriting","l":"Any","t":"Digital Age — AI Replacing Us","d":"Medium","r":4.7,"p":"Write lyrics about the anxiety of AI replacing human creativity and jobs. What happens when machines write better songs, paint better art? The existential crisis of feeling obsolete. But also — what makes us irreplaceable. The human experience no algorithm can replicate."},
    {"id":1470,"c":"Songwriting","l":"Any","t":"Digital Age — Catfished","d":"Medium","r":4.7,"p":"Write lyrics about being catfished. Falling for someone online who turned out to be completely fake. The embarrassment, the betrayal of trust, questioning your own judgment. Were the feelings real even if the person wasn't? Modern love's darkest chapter."},
    {"id":1471,"c":"Songwriting","l":"Any","t":"Digital Age — Screen Time Addiction","d":"Medium","r":4.6,"p":"Write lyrics about realising you're addicted to your phone. Hours disappearing into scrolling, real life passing you by. Can't sit in silence without reaching for it. The blue light glow replacing real sunlight. A breakup letter to your phone."},
    {"id":1472,"c":"Songwriting","l":"Any","t":"Digital Age — Online Fame","d":"Medium","r":4.7,"p":"Write lyrics about going viral and the aftermath. Overnight fame, millions of eyes on you, but it's hollow. Strangers think they know you. The pressure to stay relevant, the anxiety of one wrong post ending everything. The loneliness of being watched by millions."},
    {"id":1473,"c":"Songwriting","l":"Any","t":"Digital Age — Long Distance Love Online","d":"Medium","r":4.7,"p":"Write lyrics about falling in love with someone you've never met in person. Late-night video calls across time zones, sharing everything through screens. Planning the first meeting, the nervous anticipation. Is the real thing as good as the digital version?"},

    # === NEW THEME: CULTURAL IDENTITY ===
    {"id":1474,"c":"Songwriting","l":"Any","t":"Culture — First Generation British","d":"Medium","r":4.8,"p":"Write lyrics about being first-generation British. Parents from another country, raised between two worlds. Speaking one language at home, another outside. The pressure to succeed for the family who sacrificed everything. Navigating dual identity with pride."},
    {"id":1475,"c":"Songwriting","l":"Any","t":"Culture — Caribbean Heritage","d":"Medium","r":4.7,"p":"Write lyrics celebrating Caribbean heritage and roots. Carnival culture, patois at grandma's house, rice and peas on Sunday. The warmth and strength of Caribbean community in the UK. Missing the islands you've only visited but feel deeply connected to."},
    {"id":1476,"c":"Songwriting","l":"Any","t":"Culture — South Asian Expectations","d":"Medium","r":4.7,"p":"Write lyrics about navigating South Asian family expectations. The pressure of arranged introductions, career paths chosen for you, honour and duty. Finding your own voice while respecting your roots. The generation gap that's really a cultural canyon. Balancing love and obligation."},
    {"id":1477,"c":"Songwriting","l":"Any","t":"Culture — African Diaspora Pride","d":"Medium","r":4.8,"p":"Write lyrics celebrating African diaspora culture. The richness of heritage, the traditions that survived slavery and colonialism. Food, music, language, dance passed down through generations. Reclaiming history and wearing it like a crown. Ancestral pride."},

    # === NEW THEME: WORKING CLASS ===
    {"id":1478,"c":"Songwriting","l":"Any","t":"Working Class — Zero Hours Contract","d":"Medium","r":4.7,"p":"Write lyrics about surviving on zero-hours contracts. Never knowing if you'll work next week, can't plan anything, treated as disposable. The anxiety of checking your phone for shifts. Bills don't care about your schedule. Modern-day exploitation with a corporate smile."},
    {"id":1479,"c":"Songwriting","l":"Any","t":"Working Class — Night Shift Life","d":"Medium","r":4.7,"p":"Write lyrics about working the night shift. While the world sleeps, you're grafting. Missing birthdays, sleeping when everyone's awake, living in reverse. The quiet camaraderie of night workers. Coming home as the sun rises. The invisible workforce."},
    {"id":1480,"c":"Songwriting","l":"Any","t":"Working Class — Council Estate Pride","d":"Medium","r":4.8,"p":"Write lyrics about being proud of your council estate upbringing. The community that raised you, the resilience you learned. Outsiders see poverty — you see family. The best people you know came from the worst postcodes. Redefining what it means to come from nothing."},
    {"id":1481,"c":"Songwriting","l":"Any","t":"Working Class — Minimum Wage Dreams","d":"Medium","r":4.7,"p":"Write lyrics about dreaming big while earning minimum wage. Stacking shelves by day, writing bars by night. The soul-crushing gap between where you are and where you want to be. Using the frustration as fuel. One day this won't be your life."},

    # === RELATIONSHIP EXPANDED ===
    {"id":1482,"c":"Songwriting","l":"Any","t":"Relationship — Trust Issues","d":"Medium","r":4.8,"p":"Write lyrics about being unable to fully trust a new partner because of past betrayal. They've done nothing wrong but you're waiting for the other shoe to drop. Checking their phone in your head, reading into every late reply. Sabotaging something good because someone else broke you."},
    {"id":1483,"c":"Songwriting","l":"Any","t":"Relationship — Different Worlds","d":"Medium","r":4.7,"p":"Write lyrics about being in love with someone from a completely different background. Class divide, cultural differences, families who don't approve. You fit perfectly in private but the outside world keeps reminding you that you're 'different.' Love as rebellion."},
    {"id":1484,"c":"Songwriting","l":"Any","t":"Relationship — Toxic Masculinity","d":"Medium","r":4.7,"p":"Write lyrics about a man learning to be vulnerable in a relationship. Raised not to cry, not to feel, be strong always. She's asking him to open up and he doesn't know how. The walls built by boyhood. Unlearning toughness to discover tenderness."},
    {"id":1485,"c":"Songwriting","l":"Any","t":"Relationship — Long Term Boredom","d":"Medium","r":4.6,"p":"Write lyrics about the boredom that creeps into long relationships. Same routines, same conversations, the spark feels distant. But also — is comfort being undervalued? The choice to reignite versus the temptation to start fresh. Real talk about the unglamorous side of love."},
    {"id":1486,"c":"Songwriting","l":"Any","t":"Relationship — Falling for Your Best Friend","d":"Medium","r":4.8,"p":"Write lyrics about catching feelings for your best friend. The terror of ruining what you have. Every hug lasting a beat too long, every joke feeling like flirting. Should you risk the friendship for something more? The most beautiful gamble."},

    # === PARTY & CELEBRATION EXPANDED ===
    {"id":1487,"c":"Songwriting","l":"Any","t":"Party — Pre-Drinks Energy","d":"Simple","r":4.7,"p":"Write lyrics about pre-drinks before going out. Getting ready with your crew, music blasting, outfits being decided. The excitement of the night ahead, shots flowing, everyone hyping each other up. This is often better than the actual club. Anticipation anthem."},
    {"id":1488,"c":"Songwriting","l":"Any","t":"Party — Festival Weekend","d":"Simple","r":4.8,"p":"Write lyrics about a festival weekend. Tents, mud, sunburn, and pure freedom. No signal, no stress, just music and mates. The moments between sets — meeting strangers who become friends, sunrise at the main stage. Three days of existing outside real life."},
    {"id":1489,"c":"Songwriting","l":"Any","t":"Party — Birthday Anthem","d":"Simple","r":4.7,"p":"Write lyrics for an ultimate birthday anthem. It's your day, everything revolves around you. The cake, the surprises, the people who showed up. Celebrating surviving another year. VIP energy, main character moment. Make it a universal birthday banger."},

    # === NOSTALGIA EXPANDED ===
    {"id":1490,"c":"Songwriting","l":"Any","t":"Nostalgia — School Days","d":"Medium","r":4.7,"p":"Write lyrics about missing school days. The simplicity, the drama that felt enormous, friends you've lost touch with. Playground politics, passing notes, the walk home. You didn't know those were the best days while you were living them. Aching for innocence."},
    {"id":1491,"c":"Songwriting","l":"Any","t":"Nostalgia — Early 2000s Childhood","d":"Medium","r":4.7,"p":"Write lyrics about growing up in the early 2000s. MSN Messenger, Limewire, PS2, Saturday morning TV. Before smartphones changed everything. Specific references that hit millennial/early Gen Z nostalgia. The last generation to play outside AND grow up online."},
    {"id":1492,"c":"Songwriting","l":"Any","t":"Nostalgia — Grandma's House","d":"Simple","r":4.8,"p":"Write lyrics about the magic of your grandma's house. The smell of cooking, the plastic-covered sofa, biscuit tin that never had biscuits. The safest place in the world. Specific sensory details — her perfume, the TV always too loud, her hands. A love letter to grandmothers."},
    {"id":1493,"c":"Songwriting","l":"Any","t":"Nostalgia — Summer as a Kid","d":"Simple","r":4.8,"p":"Write lyrics about endless childhood summers. Six weeks felt like forever. Water fights, ice cream vans, staying out until dark. No responsibilities, pure freedom. The grass-stained knees, the sunburn, the exhaustion of a day fully lived. You'd give anything for one more."},

    # === NEW THEME: NATURE & ENVIRONMENT ===
    {"id":1494,"c":"Songwriting","l":"Any","t":"Nature — Ocean Meditation","d":"Simple","r":4.7,"p":"Write lyrics using the ocean as a metaphor for emotions. Calm surfaces hiding depths, waves of feeling crashing then retreating. The therapeutic power of being near water. Tides as life's cycles. Surrender to the current. Peaceful yet powerful."},
    {"id":1495,"c":"Songwriting","l":"Any","t":"Nature — Climate Anxiety","d":"Medium","r":4.7,"p":"Write lyrics about eco-anxiety and climate grief. Watching the planet burn while scrolling on phones made from its resources. The helplessness of caring about something everyone ignores. Forests falling, oceans rising, politicians stalling. Angry and mourning simultaneously."},
    {"id":1496,"c":"Songwriting","l":"Any","t":"Nature — Concrete Jungle Escape","d":"Medium","r":4.7,"p":"Write lyrics about escaping the city for nature. Concrete to green, noise to silence, screens to skies. The physical relief of fresh air after weeks of pollution. A weekend in the countryside healing months of urban stress. The pull between where you need to be and where you need to go."},

    # === STORYTELLING EXPANDED ===
    {"id":1497,"c":"Songwriting","l":"Any","t":"Storytelling — The Dealer Who Wants Out","d":"Advanced","r":4.8,"p":"Write a narrative track about a drug dealer trying to go legit. Every time they try to leave, something pulls them back — debts, loyalty, threats. Three verses, three attempts to escape. The tragedy of a cycle that won't break. Humanising without glorifying."},
    {"id":1498,"c":"Songwriting","l":"Any","t":"Storytelling — Two Strangers on a Train","d":"Medium","r":4.7,"p":"Write lyrics telling the story of two strangers who share a train journey. Brief conversation that changes both their lives. Different backgrounds, unexpected connection. They never exchange names. Verse 1 is her story, Verse 2 is his, Verse 3 is their shared moment. Beautiful and fleeting."},
    {"id":1499,"c":"Songwriting","l":"Any","t":"Storytelling — The Nurse's Shift","d":"Advanced","r":4.8,"p":"Write lyrics following a nurse through a 12-hour shift. The lives they hold, the deaths they witness, the impossible choices. Heroism that looks like exhaustion. Specific scenes — comforting a scared patient, calling time of death, then going home and pretending everything's normal. Tribute to healthcare workers."},
    {"id":1500,"c":"Songwriting","l":"Any","t":"Storytelling — Childhood Best Friends","d":"Medium","r":4.8,"p":"Write lyrics tracking two childhood best friends over 20 years. Inseparable kids, drifting teenagers, reconnecting adults. Verse 1: age 8, building dens. Verse 2: age 16, different paths. Verse 3: age 28, meeting for a drink and realising nothing's changed. Time-lapse friendship."},
    {"id":1501,"c":"Songwriting","l":"Any","t":"Storytelling — Last Day of a Soldier","d":"Advanced","r":4.8,"p":"Write lyrics following a soldier's last day before deployment. Morning with family, the things left unsaid, the brave face. Writing a letter just in case. The drive to the base, looking back at home in the mirror. Not anti-war propaganda — personal and human. The weight of service."},

    # === NEW THEME: SELF-DISCOVERY ===
    {"id":1502,"c":"Songwriting","l":"Any","t":"Self-Discovery — Quarter Life Crisis","d":"Medium","r":4.7,"p":"Write lyrics about the quarter-life crisis. Mid-twenties, expected to have it figured out but you're more lost than ever. Comparing yourself to others' highlights. Career confusion, relationship uncertainty, existential dread in a rented flat. Everyone's faking it — right?"},
    {"id":1503,"c":"Songwriting","l":"Any","t":"Self-Discovery — Leaving Religion","d":"Advanced","r":4.7,"p":"Write lyrics about leaving a religion you were raised in. The guilt, the freedom, the loss of community. Questioning everything you were taught. Family relationships strained. Finding your own moral compass without a holy book. Liberating and lonely in equal measure."},
    {"id":1504,"c":"Songwriting","l":"Any","t":"Self-Discovery — Coming Out","d":"Medium","r":4.8,"p":"Write lyrics about coming out — whatever that means for the individual. The years of hiding, the fear of rejection, the moment of truth. The relief and terror of being seen. Not everyone's reaction will be love. But being yourself is no longer optional. Brave and necessary."},
    {"id":1505,"c":"Songwriting","l":"Any","t":"Self-Discovery — Therapy Breakthrough","d":"Medium","r":4.7,"p":"Write lyrics about having a breakthrough moment in therapy. The wall you've been hitting suddenly crumbles. Understanding why you do what you do. The ugly cry that's actually beautiful. The terrifying relief of finally getting it. A before and after moment."},
    {"id":1506,"c":"Songwriting","l":"Any","t":"Self-Discovery — Solo Travel","d":"Medium","r":4.7,"p":"Write lyrics about travelling alone for the first time. Terrifying freedom, eating alone, navigating foreign places with just yourself. Who are you when nobody knows your name? The conversations with strangers, the silence with yourself. Coming home as someone new."},

    # === NEW THEME: GENERATIONAL ===
    {"id":1507,"c":"Songwriting","l":"Any","t":"Generational — Letter to My Younger Self","d":"Medium","r":4.8,"p":"Write lyrics as a letter to your younger self. The warnings, the reassurances, the things you wish they knew. Don't worry about the bullies, the heartbreak heals, that dream does come true. Tender and specific. What age would you write to? What would you change?"},
    {"id":1508,"c":"Songwriting","l":"Any","t":"Generational — Millennials vs Boomers","d":"Medium","r":4.6,"p":"Write lyrics about generational conflict with humour and truth. Boomers say entitled, millennials say exploited. Avocado toast economics, housing market reality, 'back in my day' vs 'OK boomer.' Not mean-spirited — finding common ground beneath the stereotypes."},
    {"id":1509,"c":"Songwriting","l":"Any","t":"Generational — Gen Z Anthem","d":"Simple","r":4.7,"p":"Write lyrics that capture the Gen Z experience. Growing up in chaos — pandemic, climate crisis, political polarisation — but also the most connected, creative, and aware generation yet. TikTok philosophers, side hustle culture, refusing to accept the world as it is."},
    {"id":1510,"c":"Songwriting","l":"Any","t":"Generational — Raising Kids in This World","d":"Medium","r":4.7,"p":"Write lyrics about the fear and hope of raising children today. School shootings, online predators, climate change — but also kindness, technology, possibility. Wanting to protect them from everything while knowing you can't. The impossible job of modern parenting."},

    # === DARK EXPANDED ===
    {"id":1511,"c":"Songwriting","l":"Any","t":"Dark — Intrusive Thoughts","d":"Advanced","r":4.7,"p":"Write lyrics about intrusive thoughts — the dark, involuntary thoughts that flash through your mind. Not who you are but what your brain tortures you with. The shame of having thoughts you'd never act on. The exhausting mental battle of OCD and intrusive thinking. Destigmatising and honest."},
    {"id":1512,"c":"Songwriting","l":"Any","t":"Dark — The Narcissist","d":"Medium","r":4.7,"p":"Write lyrics from the perspective of someone escaping a narcissistic relationship. Gaslighting, love-bombing, the cycle of idealise and discard. Slowly realising the love was manipulation. The painful recovery of learning to trust yourself again. Survival anthem."},
    {"id":1513,"c":"Songwriting","l":"Any","t":"Dark — Haunted House Mind","d":"Medium","r":4.7,"p":"Write lyrics comparing your mind to a haunted house. Each room holds a different trauma, ghosts of past selves wandering corridors. Some doors you've locked and lost the key. Visitors only see the exterior. Living in a place you can never fully leave."},
    {"id":1514,"c":"Songwriting","l":"Any","t":"Dark — Stalker Perspective","d":"Advanced","r":4.6,"p":"Write lyrics exploring obsession from a disturbing perspective. Not glorifying — exposing the twisted logic. Every action justified in their mind. Watching, waiting, collecting details. The horror of being someone's fixation. Uncomfortable but important storytelling."},

    # === MORE GENRE-SPECIFIC ===
    {"id":1515,"c":"Songwriting","l":"Any","t":"Drill — Court Date Tomorrow","d":"Advanced","r":4.7,"p":"Write drill lyrics about facing court tomorrow. The sleepless night before, going through scenarios. Suit pressed, barrister prepped, but nothing's guaranteed. Your mum's face in the gallery. The system that's not built for you. Real stakes, real consequences. UK drill reality."},
    {"id":1516,"c":"Songwriting","l":"Any","t":"Drill — New Generation","d":"Medium","r":4.7,"p":"Write drill lyrics about being the new generation of UK drill. Paying respect to pioneers while pushing the sound forward. Fresh flows, new energy, same streets. Not just violence — drill as a voice for the voiceless. Evolving the genre."},
    {"id":1517,"c":"Songwriting","l":"Any","t":"R&B — Friends with Benefits","d":"Medium","r":4.7,"p":"Write R&B lyrics about a friends-with-benefits situation going wrong. Someone caught feelings, probably you. The rules were clear but hearts don't follow rules. Pretending casual when it's anything but. The conversation you need to have but are terrified of."},
    {"id":1518,"c":"Songwriting","l":"Any","t":"R&B — Morning After","d":"Simple","r":4.7,"p":"Write R&B lyrics about the morning after spending the night together for the first time. Sun through curtains, them sleeping peacefully, not wanting to move. Breakfast together, shy smiles, replaying last night. The gentle intimacy of morning light. Tender and warm."},
    {"id":1519,"c":"Songwriting","l":"Any","t":"Pop — Revenge Glow Up","d":"Simple","r":4.8,"p":"Write pop lyrics about the ultimate revenge glow up. You got fit, got successful, got happy — and your ex is watching. Not bitter anymore, just thriving. The best version of yourself was hiding behind someone who held you back. Living well is the best revenge."},
    {"id":1520,"c":"Songwriting","l":"Any","t":"Pop — Dancing Alone","d":"Simple","r":4.7,"p":"Write pop lyrics about the freedom and joy of dancing alone. In your room, at a club, wherever — not performing for anyone but yourself. Liberation from self-consciousness. Your body knows the rhythm your brain forgot. Self-celebration through movement."},
    {"id":1521,"c":"Songwriting","l":"Any","t":"Rock — Burning Bridges","d":"Medium","r":4.7,"p":"Write rock lyrics about deliberately burning bridges. Done being diplomatic, done keeping peace. Saying everything you've held back, consequences be damned. The cathartic destruction of relationships that were holding you hostage. Liberating rage."},
    {"id":1522,"c":"Songwriting","l":"Any","t":"Rock — Last Band Standing","d":"Medium","r":4.7,"p":"Write rock lyrics about being in a band that refuses to give up. Decades of playing to empty rooms, one hit wonder almost, industry rejection. But the music keeps you alive. Four people against the world. The romantic stubbornness of believing in your art."},
    {"id":1523,"c":"Songwriting","l":"Any","t":"Country — Weathered Hands","d":"Medium","r":4.7,"p":"Write country lyrics about a father's weathered hands. The calluses from years of manual labour, the tenderness those same hands showed. Building, fixing, providing — never complaining. A tribute to blue-collar fathers through the detail of their hands."},
    {"id":1524,"c":"Songwriting","l":"Any","t":"Country — Front Porch Memories","d":"Simple","r":4.7,"p":"Write country lyrics about sitting on the front porch with family. Generations of stories told in the same rocking chairs. Lightning bugs, sweet tea, guitar picked lazily. The tradition of porches as places where life happens. Timeless and grounded."},
    {"id":1525,"c":"Songwriting","l":"Any","t":"Gospel — Testimony","d":"Medium","r":4.7,"p":"Write gospel lyrics sharing a personal testimony. Where you were in the darkness, how faith found you, where you are now. Specific and authentic — not just 'I was lost, now I'm found' but the actual story. The congregation should feel your journey. Powerful witness."},
    {"id":1526,"c":"Songwriting","l":"Any","t":"Gospel — Sunday Morning Praise","d":"Simple","r":4.7,"p":"Write gospel praise lyrics for Sunday morning worship. Joyful, uplifting, hands-raised energy. Thanking God for waking up, for breath, for blessings seen and unseen. Congregational — everyone can sing along. The church as sanctuary. Pure celebration of faith."},

    # === NEW THEME: SPORTS & COMPETITION ===
    {"id":1527,"c":"Songwriting","l":"Any","t":"Sports — Underdog Championship","d":"Medium","r":4.7,"p":"Write lyrics from the perspective of an underdog athlete in the championship moment. Years of training, everyone counted you out, this is your shot. The crowd noise fading to silence as you focus. One moment to change everything. Rocky meets real life. Cinematic triumph."},
    {"id":1528,"c":"Songwriting","l":"Any","t":"Sports — Injury Comeback","d":"Medium","r":4.7,"p":"Write lyrics about an athlete recovering from a career-threatening injury. The surgery, the rehab, the dark days of wondering if you'll ever compete again. The first time you run again, play again, compete again. Comeback stories are the greatest stories."},
    {"id":1529,"c":"Songwriting","l":"Any","t":"Sports — Last Game Ever","d":"Medium","r":4.8,"p":"Write lyrics about playing your final game before retirement. Looking around the stadium one last time. The roar you'll never hear again. Teammates who became family. Taking off the shirt for the last time. Identity crisis — who are you without this? Bittersweet farewell."},

    # === ANGER EXPANDED ===
    {"id":1530,"c":"Songwriting","l":"Any","t":"Anger — Workplace Rage","d":"Medium","r":4.7,"p":"Write lyrics about workplace frustration. The boss who takes credit, the meetings that should be emails, the performance review that's a joke. Corporate gaslighting wrapped in HR speak. The fantasy of telling them all exactly what you think. Office rebellion anthem."},
    {"id":1531,"c":"Songwriting","l":"Any","t":"Anger — Gaslighting Exposé","d":"Medium","r":4.8,"p":"Write lyrics calling out a gaslighter. 'That never happened,' 'You're being crazy,' 'I never said that.' Cataloguing every lie, every manipulation, every time they made you doubt your own reality. The moment you see through it all. Empowering clarity after confusion."},
    {"id":1532,"c":"Songwriting","l":"Any","t":"Anger — Enough Is Enough","d":"Medium","r":4.8,"p":"Write lyrics about the exact moment you snap. You've been patient, understanding, forgiving — and they took that for weakness. This is the last time. The volcanic eruption after years of swallowing fire. Controlled fury that's been building since forever."},

    # === NEW THEME: PHILOSOPHICAL ===
    {"id":1533,"c":"Songwriting","l":"Any","t":"Philosophical — What Happens When We Die","d":"Advanced","r":4.7,"p":"Write lyrics exploring what happens after death. Not from a religious perspective necessarily — just honest questioning. Heaven, nothing, reincarnation, energy dispersing? The fear and the curiosity. A conversation everyone thinks about but nobody wants to have."},
    {"id":1534,"c":"Songwriting","l":"Any","t":"Philosophical — Free Will Illusion","d":"Advanced","r":4.6,"p":"Write lyrics questioning whether free will exists. Are your choices really yours or just neurons firing? The terrifying comfort of determinism. If everything's predetermined, does anything matter? Or does everything matter more? Brain-bending bars over atmospheric production."},
    {"id":1535,"c":"Songwriting","l":"Any","t":"Philosophical — Time Is a Flat Circle","d":"Advanced","r":4.7,"p":"Write lyrics about the circular nature of time and history repeating. The same mistakes, different centuries. Empires rise and fall in the same patterns. Personal cycles too — dating the same person in different bodies. Breaking the loop requires consciousness."},
    {"id":1536,"c":"Songwriting","l":"Any","t":"Philosophical — Simulation Theory","d":"Medium","r":4.6,"p":"Write lyrics exploring simulation theory. What if none of this is real? Glitches in the matrix — déjà vu, coincidences too perfect, the uncanny feeling that someone's watching. Playful but genuinely philosophical. The existential crisis of the digital age."},

    # === EMPOWERMENT EXPANDED ===
    {"id":1537,"c":"Songwriting","l":"Any","t":"Empowerment — Body Positivity","d":"Medium","r":4.8,"p":"Write lyrics celebrating your body exactly as it is. Stretch marks as tiger stripes, scars as stories, every curve and edge earned. Rejecting photoshop standards, embracing the mirror. Not aspirational — present tense. You're not working towards beautiful — you already are."},
    {"id":1538,"c":"Songwriting","l":"Any","t":"Empowerment — Single and Thriving","d":"Simple","r":4.7,"p":"Write lyrics about genuinely loving single life. Not settling, not searching, just living. The freedom of answering to nobody. Travelling alone, eating what you want, sleeping diagonally. Society says you need a partner — you disagree. Wholeness without a plus-one."},
    {"id":1539,"c":"Songwriting","l":"Any","t":"Empowerment — Reclaiming Your Name","d":"Medium","r":4.8,"p":"Write lyrics about reclaiming your reputation after it was dragged through the mud. Rumours, lies, cancellation attempts — and you survived all of it. They said who you are but they were wrong. Now you're defining yourself on your own terms. Resurrection anthem."},

    # === FAMILY EXPANDED ===
    {"id":1540,"c":"Songwriting","l":"Any","t":"Family — Divorce Kid","d":"Medium","r":4.8,"p":"Write lyrics from the perspective of a child of divorce. Two houses, two Christmases, the suitcase always packed. Being caught in the middle of adult problems. The guilt of loving both parents while they hate each other. Growing up fast because you had to."},
    {"id":1541,"c":"Songwriting","l":"Any","t":"Family — Estranged Parent Reunion","d":"Advanced","r":4.8,"p":"Write lyrics about meeting an estranged parent after years of no contact. The anger, the hope, the questions. Do you want an explanation or an apology? Can you forgive? The awkward coffee, the lifetime of silence between sentences. Emotionally complex reunion."},
    {"id":1542,"c":"Songwriting","l":"Any","t":"Family — Brother's Keeper","d":"Medium","r":4.7,"p":"Write lyrics about protecting a younger sibling from the same mistakes you made. Steering them away from the roads, the people, the choices that nearly destroyed you. The fear of them not listening. You failed so they wouldn't have to. Guardian angel in human form."},
    {"id":1543,"c":"Songwriting","l":"Any","t":"Family — Foster Care Story","d":"Advanced","r":4.8,"p":"Write lyrics about growing up in the foster care system. Moving homes, never unpacking fully, learning not to get attached. The social workers, the other kids, the families that were temporary. Searching for belonging in a system designed for survival, not love."},

    # === LOSS EXPANDED ===
    {"id":1544,"c":"Songwriting","l":"Any","t":"Loss — Empty Chair at Christmas","d":"Advanced","r":4.9,"p":"Write lyrics about the first Christmas after losing someone. Their stocking still hung, their favourite song on the radio, the seat nobody sits in. The family trying to be festive through grief. The cruelest holiday when someone's missing. Devastating and deeply specific."},
    {"id":1545,"c":"Songwriting","l":"Any","t":"Loss — Miscarriage","d":"Advanced","r":4.9,"p":"Write lyrics about the grief of miscarriage. A loss that society doesn't fully acknowledge. The nursery that won't be used, the name that won't be called, the future that vanished. The isolation of grieving someone the world never met. Tender, honest, necessary."},
    {"id":1546,"c":"Songwriting","l":"Any","t":"Loss — Losing a Pet","d":"Medium","r":4.8,"p":"Write lyrics about losing a beloved pet. The house suddenly silent, their spot on the sofa empty. They were family — anyone who says 'it's just an animal' never loved one. The unconditional love that's impossible to replace. They were the best part of coming home."},
    {"id":1547,"c":"Songwriting","l":"Any","t":"Loss — Dementia Goodbye","d":"Advanced","r":4.9,"p":"Write lyrics about watching someone you love disappear into dementia. They're physically here but mentally gone. The moments of clarity that break your heart worse. Grieving someone who's still alive. The cruelest kind of loss — gradual and relentless. For all the families watching someone fade."},

    # === NEW THEME: NIGHT LIFE ===
    {"id":1548,"c":"Songwriting","l":"Any","t":"Night Life — Last Orders","d":"Medium","r":4.7,"p":"Write lyrics about last orders at the pub. The bartender calling time, not ready for the night to end. Deep conversations that only happen after midnight. Stumbling out into cold air, kebab shop pilgrimage, the walk home with your best mate. British nightlife ritual."},
    {"id":1549,"c":"Songwriting","l":"Any","t":"Night Life — The Bouncer","d":"Medium","r":4.6,"p":"Write lyrics from a nightclub bouncer's perspective. They see everything — the fights, the tears, the proposals, the best and worst of people. Standing in the cold all night, judging shoes and attitudes. The stories nobody tells from the door. Observational and human."},
    {"id":1550,"c":"Songwriting","l":"Any","t":"Night Life — 5AM Walk Home","d":"Medium","r":4.7,"p":"Write lyrics about the 5AM walk home alone after a night out. The city empty, your thoughts loud. Slightly drunk, slightly philosophical. The strange beauty of dawn breaking over empty streets. Fast food wrapper tumbling in the wind. Liminal space between night and day."},

    # === EMOTIONAL EXPANDED ===
    {"id":1551,"c":"Songwriting","l":"Any","t":"Emotional — Happy Crying","d":"Simple","r":4.7,"p":"Write lyrics about crying from happiness. Those overwhelming moments — a wedding, a birth, achieving the impossible. Tears that taste different, that feel like release and celebration. The world blurring through joy. It's okay to fall apart when life comes together."},
    {"id":1552,"c":"Songwriting","l":"Any","t":"Emotional — Grief Comes in Waves","d":"Medium","r":4.8,"p":"Write lyrics about how grief ambushes you. You're fine for weeks, then a song or a smell or a Tuesday afternoon shatters you. Grief isn't linear — it's a tide that retreats and crashes without warning. Learning to swim in an ocean that appeared overnight."},
    {"id":1553,"c":"Songwriting","l":"Any","t":"Emotional — The Good Days","d":"Simple","r":4.8,"p":"Write lyrics celebrating the good days. Not milestones — just regular Tuesdays where everything clicks. You slept well, traffic was kind, someone smiled at you. The quiet victories that don't make highlight reels but make life worth living. Gratitude for the ordinary."},
    {"id":1554,"c":"Songwriting","l":"Any","t":"Emotional — Numb","d":"Medium","r":4.7,"p":"Write lyrics about emotional numbness. Not sadness — the absence of feeling anything at all. Going through life on autopilot. Everyone asks what's wrong but you genuinely don't know. The terrifying flatline of feeling nothing. Wanting to cry but your eyes forgot how."},

    # === RAP TECHNIQUE EXPANDED ===
    {"id":1555,"c":"Songwriting","l":"Any","t":"Rap — 32 Bar Storytelling Challenge","d":"Advanced","r":4.8,"p":"Write a full 32-bar rap with a complete story arc. Setup, conflict, climax, resolution — all in 32 bars. Every line should matter, no filler. Tight internal rhyme scheme, vivid imagery, character development. A short film in bars. Ultimate pen game test."},
    {"id":1556,"c":"Songwriting","l":"Any","t":"Rap — Concept: Reverse Chronology","d":"Advanced","r":4.7,"p":"Write rap verses telling a story backwards. Start at the end — the consequence — and work back to the beginning — the choice. Each verse rewinds further. By the final verse, the listener understands how it all started. Memento in bar form. Structural creativity."},
    {"id":1557,"c":"Songwriting","l":"Any","t":"Rap — Battle Bars Blueprint","d":"Advanced","r":4.7,"p":"Write 16 bars of battle rap designed to win a clash. Personal yet universal enough to use. Devastating punchlines, name-flipping potential, crowd-reaction bars. Study Don't Flop and King of the Dot. Each bar should be quotable. Designed for the ring."},
    {"id":1558,"c":"Songwriting","l":"Any","t":"Rap — Conscious Bars","d":"Advanced","r":4.8,"p":"Write 16 bars of conscious rap addressing a social issue. Educational without being boring, lyrical without sacrificing message. Facts woven into flow. Lowkey meets Immortal Technique. Make the listener think while their head nods. Substance and style equally."},

    # === HOOK & SONGCRAFT EXPANDED ===
    {"id":1559,"c":"Songwriting","l":"Any","t":"Song Structure — Verse Chorus Bridge","d":"Simple","r":4.7,"p":"Write a complete song structure — Verse 1, Pre-Chorus, Chorus, Verse 2, Pre-Chorus, Chorus, Bridge, Final Chorus. Fill every section with lyrics. Theme: overcoming self-doubt. Show how a full song moves through emotional stages. Training wheels for complete songs."},
    {"id":1560,"c":"Songwriting","l":"Any","t":"Song Structure — No Chorus Challenge","d":"Medium","r":4.7,"p":"Write a complete song with NO chorus. Three verses that build on each other, bridges connecting them, outro that serves as climax. Prove you don't need a hook to keep people listening. Through-composed songwriting. Storytelling that doesn't repeat."},
    {"id":1561,"c":"Songwriting","l":"Any","t":"Hooks — Question Hooks","d":"Medium","r":4.7,"p":"Generate 10 hook ideas that are questions. Questions as choruses are powerful — they make the listener answer internally. 'Is anybody out there?', 'What if I told you?', 'Why does it always rain on me?' Format. Mix rhetorical and genuine. Universal questioning."},
    {"id":1562,"c":"Songwriting","l":"Any","t":"Hooks — Single Word Hooks","d":"Simple","r":4.7,"p":"Generate 10 hook concepts built around a single repeated word. Like 'Stay', 'Closer', 'Help', 'Breathe.' The word carries the weight, the melody makes it emotional. Simple, powerful, universal. Show how one word can be an entire chorus with the right delivery."},
    {"id":1563,"c":"Songwriting","l":"Any","t":"Pre-Chorus — Tension Builders","d":"Medium","r":4.7,"p":"Write 10 pre-chorus sections designed to build tension before a big chorus lands. The musical lift, the lyrical pivot, the moment that makes the chorus hit harder. Study how Billie Eilish, The Weeknd, and Adele use pre-choruses. The unsung hero of song structure."},
    {"id":1564,"c":"Songwriting","l":"Any","t":"Outros — Lasting Impressions","d":"Medium","r":4.6,"p":"Write 10 outro sections that leave lasting impressions. The final words of a song matter — they echo in the listener's mind. Whispered confessions, repeated mantras, unexpected twists. How you end is what people remember. The art of closing a song."},

    # === NEW THEME: DREAM & SURREAL ===
    {"id":1565,"c":"Songwriting","l":"Any","t":"Surreal — Lucid Dream","d":"Medium","r":4.6,"p":"Write lyrics about a lucid dream where you control everything. Flying over cities, talking to the dead, reshaping reality. But the alarm is coming. The desperate attempt to stay asleep, to hold onto a world better than waking. The cruelty of consciousness."},
    {"id":1566,"c":"Songwriting","l":"Any","t":"Surreal — Parallel Universe","d":"Medium","r":4.6,"p":"Write lyrics imagining a parallel universe where you made different choices. The other you who said yes, who stayed, who left, who tried. Is that version happier? Are you better off? The infinite 'what ifs' of multiverse thinking. Speculative and emotional."},
    {"id":1567,"c":"Songwriting","l":"Any","t":"Surreal — Conversation with Death","d":"Advanced","r":4.7,"p":"Write lyrics as a conversation with Death personified. Not scary — almost friendly. Death as a patient companion who's been walking beside you your whole life. Questions and answers about life's meaning, what's on the other side, why now. Philosophical and haunting."},

    # === NEW THEME: MONEY & AMBITION ===
    {"id":1568,"c":"Songwriting","l":"Any","t":"Money — From Benefits to Business","d":"Medium","r":4.7,"p":"Write lyrics about going from government benefits to running your own business. The shame they tried to put on you, the hustle nobody saw, the paperwork, the risk. Now you employ people who look like you came from where you came from. Ultimate glow up story."},
    {"id":1569,"c":"Songwriting","l":"Any","t":"Money — Generational Wealth","d":"Medium","r":4.7,"p":"Write lyrics about building generational wealth. Breaking the cycle of poverty. Property investments, savings accounts for kids who aren't born yet. Thinking in decades, not days. Your grandkids will never know the struggle — that's the goal. Legacy building."},
    {"id":1570,"c":"Songwriting","l":"Any","t":"Money — Rich and Empty","d":"Medium","r":4.7,"p":"Write lyrics about achieving financial success but feeling emptier than ever. The house is big but lonely, the car is fast but going nowhere meaningful. Everyone wants your money, nobody wants you. The lie that was sold — money fixes everything. It fixes everything except the important things."},

    # === COLLABORATION CONCEPTS ===
    {"id":1571,"c":"Songwriting","l":"Any","t":"Duet — Argument Song","d":"Advanced","r":4.7,"p":"Write a male-female duet where both are arguing their side of a relationship fight. Alternating bars, interrupting each other, talking over each other. By the bridge, they stop fighting and admit what they're really scared of. Real-time conflict resolution in song form."},
    {"id":1572,"c":"Songwriting","l":"Any","t":"Duet — Ex Meets Ex","d":"Advanced","r":4.7,"p":"Write a song where two exes of the same person compare notes. They discover the same lies, same patterns, same promises. Initially bonding over shared experience, then realising the deeper truth. Sisters/brothers in heartbreak. Darkly comedic and eventually empowering."},
    {"id":1573,"c":"Songwriting","l":"Any","t":"Duet — Parent and Child Through the Years","d":"Advanced","r":4.8,"p":"Write a duet between a parent and child at different ages. Verse 1: child is 5, parent explains the world. Verse 2: child is 15, they clash. Verse 3: child is 25, they finally understand. Chorus is what they both feel but can't say. Tearjerker intergenerational love song."},

    # === SEASONAL & MOOD EXPANDED ===
    {"id":1574,"c":"Songwriting","l":"Any","t":"Mood — Sunday Evening Dread","d":"Medium","r":4.7,"p":"Write lyrics about Sunday evening dread. The weekend evaporating, Monday looming. The laundry isn't done, the meal prep wasn't prepped, and that sinking feeling in your stomach. The universal weekly grief of losing freedom. The most relatable anxious moment."},
    {"id":1575,"c":"Songwriting","l":"Any","t":"Mood — 3AM Clarity","d":"Medium","r":4.7,"p":"Write lyrics about the strange clarity that comes at 3AM. When the world is asleep and your mind is wide awake. Truths you hide in daylight become obvious. Decisions you've been avoiding become clear. The witching hour for self-reflection. Dark but enlightening."},
    {"id":1576,"c":"Songwriting","l":"Any","t":"Mood — Rain as Therapy","d":"Simple","r":4.7,"p":"Write lyrics about rain as emotional therapy. Walking in the rain deliberately, letting it wash away the noise. The soundtrack of drops on concrete, the world blurring through tears or rain — does it matter? The only weather that matches the insides of a hurting soul. Cathartic and poetic."},
    {"id":1577,"c":"Songwriting","l":"Any","t":"Mood — Golden Hour Love","d":"Simple","r":4.8,"p":"Write lyrics set during golden hour. Everything glowing amber, time slowing down. Looking at someone you love in perfect light. The magic of that 20-minute window when the world is cinematic. Warm, tender, and luminous. Photograph in song form."},

    # === GENRE FUSION EXPANDED ===
    {"id":1578,"c":"Songwriting","l":"Any","t":"Genre Fusion — Afrobeats R&B","d":"Medium","r":4.7,"p":"Write lyrics blending Afrobeats rhythm with R&B vocal melodic style. West African energy meets smooth American soul. Love song with Afrobeats foundation but R&B delivery. Perfect for artists like Burna Boy collaboration with SZA energy. Seamless genre bridge."},
    {"id":1579,"c":"Songwriting","l":"Any","t":"Genre Fusion — Grime Pop","d":"Medium","r":4.6,"p":"Write lyrics fusing grime energy with pop catchiness. Aggressive bars that melt into singable choruses. Stormzy's softer moments meet his hardest bars in one track. The contrast creates dynamics. Verse bars are grime, chorus is pop, bridge surprises everyone."},
    {"id":1580,"c":"Songwriting","l":"Any","t":"Genre Fusion — Trap Soul","d":"Medium","r":4.7,"p":"Write trap soul lyrics — the sweet spot between trap and R&B. Hard 808s but soft vocals. Street talk but pillow talk. Bryson Tiller blueprint. Vulnerable lyrics over tough production. The contrast of hard and soft that defined a generation of music."},

    # === NEW THEME: NOSTALGIA DECADES ===
    {"id":1581,"c":"Songwriting","l":"Any","t":"Decade — 90s Kid Anthem","d":"Medium","r":4.7,"p":"Write lyrics celebrating being a 90s kid. Tamagotchis, Spice Girls, SEGA vs Nintendo, recording songs off the radio. Before internet changed everything. Blockbuster Friday nights, yo-yos and pogs. The last generation of simplicity. Time capsule in song form."},
    {"id":1582,"c":"Songwriting","l":"Any","t":"Decade — 80s Synth Love","d":"Medium","r":4.6,"p":"Write lyrics that capture 80s synth-pop romance. Neon lights, slow dancing at the disco, big hair and bigger feelings. John Hughes movie energy. The innocence of analogue romance. Structurally — simple verse/chorus/verse with an emotional bridge. Retro and timeless."},
    {"id":1583,"c":"Songwriting","l":"Any","t":"Decade — 2010s Nostalgia","d":"Simple","r":4.7,"p":"Write lyrics about missing the 2010s. Vine, early Instagram, Drake's dominance, festival culture peak. Before everything got serious. The last decade of fun before the world went sideways. Specific references that hit — Snapchat streaks, aux cord battles, specific songs that defined that era."},

    # === MORE UNIQUE CONCEPTS ===
    {"id":1584,"c":"Songwriting","l":"Any","t":"Concept — Last Song Ever Written","d":"Advanced","r":4.7,"p":"Write lyrics as if this is the last song that will ever be written. Music is ending. What do you say when it's the final song humanity will hear? Everything important, everything true, compressed into one piece. A time capsule for future species. The ultimate responsibility."},
    {"id":1585,"c":"Songwriting","l":"Any","t":"Concept — Song for Someone Who Doesn't Exist Yet","d":"Medium","r":4.7,"p":"Write lyrics as a message to a future person — your unborn child, a future lover, someone you'll meet in ten years. Telling them what you needed them to know before they arrived. Welcome to my life, here's what you're walking into. Letter to the future."},
    {"id":1586,"c":"Songwriting","l":"Any","t":"Concept — The Taxi Driver Knows Everything","d":"Medium","r":4.7,"p":"Write lyrics from a taxi driver's perspective. They've heard every story — breakups, confessions, celebrations, breakdowns. The backseat is a confessional. Three verses, three different passengers, one driver who absorbs it all. The most informed stranger in the world."},
    {"id":1587,"c":"Songwriting","l":"Any","t":"Concept — Playlist for My Funeral","d":"Medium","r":4.7,"p":"Write lyrics about creating a playlist for your own funeral. What songs define your life? What mood do you want people to feel? The strange exercise of curating your own goodbye. Specific songs referenced, what they mean to you. Morbid but deeply personal."},
    {"id":1588,"c":"Songwriting","l":"Any","t":"Concept — If Walls Could Talk","d":"Medium","r":4.8,"p":"Write lyrics from the perspective of the walls of a house. Every family that's lived there, every argument, every celebration. The walls witnessed births and deaths, first steps and last breaths. Architecture as memory keeper. The stories embedded in plaster and brick."},
    {"id":1589,"c":"Songwriting","l":"Any","t":"Concept — Dear Landlord","d":"Medium","r":4.7,"p":"Write lyrics as a letter to your landlord. The mould they ignore, the rent they raise, the deposit they'll never return. Passive-aggressive sincerity. The power imbalance of the renting generation. Funny but genuinely angry. A millennial battle cry."},
    {"id":1590,"c":"Songwriting","l":"Any","t":"Concept — Living in Photographs","d":"Medium","r":4.7,"p":"Write lyrics about living through photographs. We photograph everything but experience nothing. The concert you watched through your phone screen. The meal that went cold while you got the angle right. Trading memories for content. Are you living or documenting?"},

    # === MORE UK-SPECIFIC ===
    {"id":1591,"c":"Songwriting","l":"Any","t":"UK Life — London vs Everyone","d":"Medium","r":4.7,"p":"Write lyrics about the love-hate relationship with London. The expense, the pace, the rudeness — but also the culture, the diversity, the opportunity. Can't afford to stay, can't imagine leaving. Everyone outside London doesn't understand. The capital city identity crisis."},
    {"id":1592,"c":"Songwriting","l":"Any","t":"UK Life — Northern Pride","d":"Medium","r":4.7,"p":"Write lyrics celebrating Northern England identity. Manchester, Leeds, Liverpool, Sheffield — heart and grit. The warmth of northerners, the humour, the no-nonsense attitude. Chip on the shoulder because the south gets everything. Proud of where you're from, unapologetically."},
    {"id":1593,"c":"Songwriting","l":"Any","t":"UK Life — NHS Love Letter","d":"Medium","r":4.8,"p":"Write lyrics as a love letter to the NHS. From birth to old age, always there. The nurses, the doctors, the waiting rooms at 3AM. Underfunded, understaffed, still standing. The greatest thing this country ever built. Protect it at all costs. National treasure anthem."},
    {"id":1594,"c":"Songwriting","l":"Any","t":"UK Life — Chicken Shop Date","d":"Simple","r":4.6,"p":"Write lyrics about a chicken shop date. The most British thing — meeting someone at Morley's or Sam's. Paper plates, no pretension, just vibes. If they eat wings without cutlery, they're real. The romance of unpretentious courtship. Funny, sweet, authentic."},

    # === ADDITIONAL TECHNIQUE PROMPTS ===
    {"id":1595,"c":"Songwriting","l":"Any","t":"Technique — Rhyme Scheme ABAB","d":"Simple","r":4.6,"p":"Write 16 bars using strict ABAB rhyme scheme. Every odd line rhymes with the next odd line, every even with the next even. This is the most classic and singable pattern. Theme: celebrating friendship. Technical discipline that creates natural flow."},
    {"id":1596,"c":"Songwriting","l":"Any","t":"Technique — Internal Rhyme Master","d":"Advanced","r":4.7,"p":"Write 16 bars where every single line contains at least one internal rhyme. The words within each bar rhyme with each other, not just at the end. Eminem-level internal structure. Theme: rising above haters. Technical showcase of rhyme density."},
    {"id":1597,"c":"Songwriting","l":"Any","t":"Technique — Alliteration Verse","d":"Medium","r":4.6,"p":"Write a verse heavy with alliteration — same consonant sounds starting words throughout. Not forced — naturally flowing. Like classic poetry meets modern bars. Theme: a storm as metaphor for internal chaos. Show how sound devices create mood and rhythm."},
    {"id":1598,"c":"Songwriting","l":"Any","t":"Technique — One Syllable Challenge","d":"Advanced","r":4.6,"p":"Write 8 bars using only one-syllable words. Harder than it sounds — you can't use 'about', 'because', 'together', 'remember'. The constraint forces brutal simplicity and raw clarity. Theme: heartbreak. Every word punches because every word is direct."},
    {"id":1599,"c":"Songwriting","l":"Any","t":"Technique — Extended Metaphor Song","d":"Advanced","r":4.7,"p":"Write a complete verse and chorus sustaining one extended metaphor throughout. Love as gardening, grief as ocean, success as climbing. Never break the metaphor — every line refers back to the central image. Consistent, creative, literary. Show metaphor mastery."},
    {"id":1600,"c":"Songwriting","l":"Any","t":"Technique — Perspective Switch","d":"Advanced","r":4.7,"p":"Write a song where the perspective switches mid-verse without warning. First person to second person to third person. Disorienting in the best way. The listener realises halfway through that the narrator changed. Unreliable narrator energy. Minds blown."},
]

# Read current index.html
with open('index.html', 'r', encoding='utf-8') as f:
    html = f.read()

# Find the JSON data - it's in a var D=[...] declaration
import re
# Find the closing of the PROMPTS array  
# The data line looks like: var D=[{...},{...},...];
# We need to append before the final ];

# Count current prompts
current_count = html.count('"c":')
print(f"Current prompt count: {current_count}")

# Build the new prompt JSON string
new_json = ""
for p in NEW_PROMPTS:
    new_json += ',{"id":' + str(p["id"]) + ',"c":"' + p["c"] + '","l":"' + p["l"] + '","t":"' + p["t"].replace('"', '\\"') + '","d":"' + p["d"] + '","r":' + str(p["r"]) + ',"p":"' + p["p"].replace('"', '\\"').replace("'", "\\'") + '"}'

print(f"New prompts to add: {len(NEW_PROMPTS)}")

# Find the last prompt entry before the ];  that closes the array
# The array ends with }]; before the next var
# Find the pattern: the last } before ]; in the data line
# Since the data is on one line, find 'var D=[' and locate the end

# Find where the data array ends
data_start = html.find('var D=[')
if data_start == -1:
    print("ERROR: Could not find 'var D=['")
    exit(1)

# Find the ]; that closes the array after data_start
# We need to find the matching ];
pos = data_start
bracket_count = 0
array_end = -1
found_start = False
for i in range(data_start, len(html)):
    if html[i] == '[' and not found_start:
        found_start = True
        bracket_count = 1
        continue
    if found_start:
        if html[i] == '[':
            bracket_count += 1
        elif html[i] == ']':
            bracket_count -= 1
            if bracket_count == 0:
                array_end = i
                break

if array_end == -1:
    print("ERROR: Could not find end of data array")
    exit(1)

print(f"Array ends at position {array_end}")
print(f"Character before end: '{html[array_end-1]}'")

# Insert new prompts before the closing ]
new_html = html[:array_end] + new_json + html[array_end:]

# Update prompt count in search placeholder
new_total = current_count + len(NEW_PROMPTS)
new_html = new_html.replace('Search 1450 prompts...', f'Search {new_total} prompts...')

# Verify
final_count = new_html.count('"c":')
print(f"Final prompt count: {final_count}")

with open('index.html', 'w', encoding='utf-8') as f:
    f.write(new_html)

print(f"Done! Added {len(NEW_PROMPTS)} new songwriting prompts. Total: {new_total}")
